# Kafka
bootstrap_endpoint: "localhost:9092"
time_sleep: 0

# Ingest tweets
raw_topic: "raw_tweets"
stream_rule: "news lang:en -is:retweet sample:5" # has:geo

# Ingest reddit comments
raw_topic_reddit: "raw_reddit_comments"
subreddit: "news"

# TSF data
group_id: "main_group"
negation_words: ["no", "not"]
fg_stop_words: True
fg_lemmatization: False
clean_topic: "clean_tweets"

# Clustering
cluster_topic: "cluster_texts"
num_clusters: 10

# Storage
database_name: "trend_tracker"

# Streamlit
refresh_time: 5
