# Fill in the fields then rename the file to "secret_config.yml"

TWITTER:
  BEARER_TOKEN: "XXXX"
REDDIT:
  CLIENT_ID: "XXXX"
  SECRET_TOKEN: "XXXX"
  USERNAME: "XXXX"
  PASSWORD: "XXXX"
  USER_AGENT : "StreamBot/0.0.1"