# Fill in the fields then rename the file to "secret_config.yml"

TWITTER:
  BEARER_TOKEN: "XXXX"
REDDIT:
  CLIENT_ID: "XXXX"
  CLIENT_SECRET: "XXXX"
  USERNAME: "XXXX"
  PASSWORD: "XXXX"
  USER_AGENT: "XXXX"
MONGODB:
  CONNECTION_STRING: "XXXX"
